title = "四处化圆"
baseURL = "https://arberiatheme.netlify.app/"
relativeURLs = "True"
languageCode = "en-us"
defaultContentLanguage = 'en'
theme = "arberia"

# format date. See https://gohugo.io/functions/format/
dateformat = "Monday, January 2, 2006"


# To list the most relevant pages on the front page or similar, 
# you should use the site.Params.mainSections list instead of comparing 
# section names to hard-coded values like "posts" or "post".
# [params]
#   mainSections = ['posts',]

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "JSON", "RSS", "AMP"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false
    tocMinWordCount = 100 # Minimum word count to display the Table of Contents

[markup.goldmark.renderer] # Controllare cosa faccia
  unsafe = true

[permalinks]
  posts = "/:title/"

[minify]
  minifyOutput = true

enableRobotsTXT= true


############################# Plugins ##############################
# CSS Plugins
# [[params.plugins.css]]
# link = "css/Custom.css"
# [[params.plugins.css]]
# link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"

# JS Plugins
# [[params.plugins.js]]
# link = "js/customJS.js"


# Generate favicon with https://realfavicongenerator.net/
# and copy favicon folder (name it facicon) to static/ folder
[assets]
  favicon = "favicon/favicon.ico"
  favicon16x16 = "favicon/favicon-16x16.png>"
  favicon32x32 = "favicon/favicon-32x32.png"
  apple_touch_icon = "favicon/apple-touch-icon.png"
  safari_pinned_tab = "favicon/safari-pinned-tab.svg"
  # safari_color = "18354c"
  # theme_color = "#18354c"
  # msapplication_TileColor = "#ffc40d"





######################################
[menu]
# [[menu.main]]
# identifier = "home"
# pre = ""
# post = ""
# name = "Home"
# url = "/"
# title = ""
# weight = 1

[[menu.main]]
identifier = "blog"
pre = "fa fa-drafting-compass"
post = ""
name = "博客"
url = "/posts"
title = ""
weight = 2

[[menu.main]]
identifier = "about"
pre = ""
post = ""
name = "About "
url = "/about/"
title = ""
weight = 13


# Elenco colori da usare nel  menu 
			# "color: #ff7e73;
			# "color: #abe5b1;
			# "color: #abe0e5;
			# "color: #ffc873;
			# "color: #e5c6ab;
			# "color: #b8abe5; 

# Footer config
[footer]
[[menu.footer]]
  name = "Privacy Policy"
  url = "/policy-privacy"
  weight = 1

[[menu.footer]]
  name = "Contact"
  url = "/contact"
  weight = 2


############################# social site ########################
[[params.social]]
title = "medium"
icon = "fab fa-medium-m" # fontawesome icon : https://fontawesome.com/
link = "https://medium.com/@antedoro"

[[params.social]]
title = "facebook"
icon = "fab fa-facebook-f" # fontawesome icon : https://fontawesome.com/
link = "https://www.facebook.com/antedoroguitars"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/
link = "https://twitter.com/AntedoroGuitars"

[[params.social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon : https://fontawesome.com/
link = "https://www.instagram.com/antedoroguitars/"

[[params.social]]
title = "pinterest"
icon = "fab fa-pinterest-p" # fontawesome icon : https://fontawesome.com/
link = "https://www.pinterest.it/antedoroguitars"

[[params.social]]
title = "telegram"
icon = "fab fa-telegram-plane" # fontawesome icon : https://fontawesome.com/
link = "https://telegram.me/antedoroguitars"


