#################### default params ################################

# Brand Bar (inside header)
siteBrand = true
BrandName = "四处化圆"
BrandLogo = "/images/me.jpg"
BrandBorder = "rounded" # Use rounded or rounded-circle
siteBrandWidth = 38
siteBrandHeight = 38
# siteBrandFill = "#fff"
# Unit: em
# siteBrandFontSize = 1
# siteBrandFont = "Arial"
# siteBrandFontColor = "white"

tagline = "Responsive Hugo Theme"
description = "Arberia Theme for Hugo Static Site Generator. Insert here general site description"
keywords = "Insert keywords"
author = "圆宝"
author_resume = "圆宝"

# #################### default parameters ################################
# format date. See https://gohugo.io/functions/format/
dateformat = "Monday, January 2, 2006"
# number of post on pagination list
paginate = "6"
# summary lenght on list post 
summaryLength = "225"
# default is false
disableSearch = false 
# google analytics
googleAnalytics = "UA-74607909-1" # example : UA-123-45
# YouTube Channel ID
YTChannelID = "UClA8GwWzurVCprEY6OsCvhw"
# Formspree Contact Form Link
contact_form_action = "https://formspree.io/f/mvovbvga" # go to https:formspre.io and open a free account an insert here the link
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

# #################### Social Share Buttom ################################
[social.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = true
    Whatsapp = false
    Telegram = false
    Email = true
    Pinterest = false
    Reddit = false
    Pocket = false
    Instapaper = false

